"""add_tailscale_and_reservations

Revision ID: 5411e6468053
Revises: 9121b9616e79
Create Date: 2026-05-29 12:44:26.484323
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5411e6468053'
down_revision: Union[str, None] = '9121b9616e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('reserved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('foods', sa.Column('reserved_by', sa.Integer(), nullable=True))
    op.add_column('foods', sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'foods', 'users', ['reserved_by'], ['id'])
    op.add_column('nodes', sa.Column('tailscale_ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'tailscale_ip')
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.drop_column('foods', 'reserved_at')
    op.drop_column('foods', 'reserved_by')
    op.drop_column('foods', 'reserved')
    # ### end Alembic commands ###
