"""initial schema

Revision ID: 6a885f3e4a59
Revises:
Create Date: 2026-05-29 07:18:34.710580
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a885f3e4a59"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bounties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reward_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bounties_date"), "bounties", ["date"], unique=False)
    op.create_table(
        "economy_config",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(length=255), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "entropy_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("total_entropy", sa.Float(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entropy_snapshots_ts"), "entropy_snapshots", ["ts"], unique=False)
    op.create_table(
        "food_classes",
        sa.Column("class_name", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("protein", sa.Float(), nullable=False),
        sa.Column("carbs", sa.Float(), nullable=False),
        sa.Column("lipids", sa.Float(), nullable=False),
        sa.Column("base_decay_rate", sa.Float(), nullable=False),
        sa.Column("co2_saved_g", sa.Float(), nullable=False),
        sa.Column("money_saved", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("class_name"),
    )
    op.create_table(
        "nanos_types",
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("max_level", sa.Integer(), nullable=False),
        sa.Column("base_effect", sa.Float(), nullable=False),
        sa.Column("upgrade_cost_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("type"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("location", sa.String(length=255), server_default="", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="offline", nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("xp", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "bounty_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bounty_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("claimed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bounty_id"],
            ["bounties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bounty_id", "user_id", name="uq_bounty_user"),
    )
    op.create_index(
        op.f("ix_bounty_progress_bounty_id"), "bounty_progress", ["bounty_id"], unique=False
    )
    op.create_index(
        op.f("ix_bounty_progress_user_id"), "bounty_progress", ["user_id"], unique=False
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rfid", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("claim_code", sa.String(length=32), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_rfid"), "cards", ["rfid"], unique=True)
    op.create_table(
        "foods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("food_class", sa.String(length=64), nullable=False),
        sa.Column(
            "placed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("health", sa.Float(), server_default="100", nullable=False),
        sa.Column("spoiled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("pkg_factor", sa.Float(), server_default="1", nullable=False),
        sa.Column("claimed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("claimed_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claimed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["food_class"],
            ["food_classes.class_name"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_foods_node_id"), "foods", ["node_id"], unique=False)
    op.create_table(
        "nanos_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("nanos_type", sa.String(length=32), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["nanos_type"],
            ["nanos_types.type"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "nanos_type", name="uq_user_nanos"),
    )
    op.create_index(
        op.f("ix_nanos_inventory_user_id"), "nanos_inventory", ["user_id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txn_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("items_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gains_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("xp_awarded", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_txn_id"), "transactions", ["txn_id"], unique=True)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("purity_stars", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_transaction_id"), "feedback", ["transaction_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_transaction_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_txn_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_nanos_inventory_user_id"), table_name="nanos_inventory")
    op.drop_table("nanos_inventory")
    op.drop_index(op.f("ix_foods_node_id"), table_name="foods")
    op.drop_table("foods")
    op.drop_index(op.f("ix_cards_rfid"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_bounty_progress_user_id"), table_name="bounty_progress")
    op.drop_index(op.f("ix_bounty_progress_bounty_id"), table_name="bounty_progress")
    op.drop_table("bounty_progress")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("nodes")
    op.drop_table("nanos_types")
    op.drop_table("food_classes")
    op.drop_index(op.f("ix_entropy_snapshots_ts"), table_name="entropy_snapshots")
    op.drop_table("entropy_snapshots")
    op.drop_table("economy_config")
    op.drop_index(op.f("ix_bounties_date"), table_name="bounties")
    op.drop_table("bounties")
    # ### end Alembic commands ###
