"""user material balances

Revision ID: 7f908ca59045
Revises: 6a885f3e4a59
Create Date: 2026-05-29 08:04:53.427219
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f908ca59045"
down_revision: str | None = "6a885f3e4a59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("protein", sa.Float(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("carbs", sa.Float(), server_default="0", nullable=False))
    op.add_column("users", sa.Column("lipids", sa.Float(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lipids")
    op.drop_column("users", "carbs")
    op.drop_column("users", "protein")
    # ### end Alembic commands ###
