"""food_classes display_name_zh

Revision ID: 9121b9616e79
Revises: 7f908ca59045
Create Date: 2026-05-29 10:58:02.138704
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9121b9616e79"
down_revision: str | None = "7f908ca59045"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "food_classes",
        sa.Column("display_name_zh", sa.String(length=128), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("food_classes", "display_name_zh")
    # ### end Alembic commands ###
